token:
  # 令牌有效期（默认30分钟）
  time: 7
  # SECONDS 秒  MINUTES 分钟 HOURS 小时 DAYS 天
  expireType: DAYS
  # 令牌自定义标识
  header: token
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
server:
  port: 8899
  servlet:
    context-path: /gaoshan
spring:
  profiles:
    active: dev
  # 格式化全局时间字段
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379`
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.gaoshan.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:gaoshanMapper/**/*Mapper.xml

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /
wx:
  appid: wx00c3ff92f7992758
  secret: 337b95b46597201c147553f1ee83cd06
# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.4.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
